<?php
$sql_create = array(
		'CREATE table IF NOT EXISTS `'.$wpdb->prefix.'jwp_settings`(
		`id` int(10) NOT NULL AUTO_INCREMENT,
		`jwp_action` varchar(2),
		`c_post_name` varchar(100),
		`c_post_sname` varchar(100),
		`c_post_lname` varchar(100),
		`c_post_add_lname` varchar(100),
		`c_post_edit_lname` varchar(100),
		`c_post_newI_lname` varchar(100),
		`c_post_viewI_lname` varchar(100),
		`c_post_searchI_lname` varchar(100),
		`c_post_404_lname` varchar(100),
		`c_post_404t_lname` varchar(100),
		`c_post_public` varchar(1),
		`c_post_publicQ` varchar(1),
		`c_post_showUI` varchar(1),
		`c_post_archieve` varchar(1),
		`c_post_Qvar` varchar(1),
		`c_post_icon` varchar(255),
		`c_post_rewrite` varchar(1),
		`c_post_captype` varchar(10),
		`c_post_hierarchical` varchar(10),
		`c_post_menupos` varchar(4),
		`c_post_s_title` varchar(1),
		`c_post_s_editor` varchar(1),
		`c_post_s_author` varchar(1),
		`c_post_s_thumbnail` varchar(1),
		`c_post_s_excerpt` varchar(1),
		`c_post_s_trackbacks` varchar(1),
		`c_post_s_customF` varchar(1),
		`c_post_s_comments` varchar(1),
		`c_post_s_revisions` varchar(1),
		`c_post_s_page_attributes` varchar(1),
		`c_post_s_post_formats` varchar(1),
		`tax_c_post_name` varchar(100),
		`tax_c_post_label` varchar(100),
		`tax_c_post_s_label` varchar(100),
		`slide_target` varchar(255),
		`slide_autoplay` varchar(1),
		`slide_speed` int(10),
		`lightview` varchar(1),
		`widget_sidebar_title` varchar(255),
		`widget_sidebar_id` varchar(255),
		`widget_sidebar_desc` varchar(255),
		`cmenu_location` varchar(255),
		`cmenu_name` varchar(255),
		`cimage_name` varchar(255),
		`cimage_w` int(5),
		`cimage_h` int(5),
		`newsletter_name` varchar(1),
		`newsletter_email` varchar(1),
		`mb_value` text, 
		 primary key(id)
	)');

?>